### ISSUE TITLE
Incorrect reference

### ISSUE THREAD

**Issue by markhedleyjones** [MarkHedleyJones/paper_autonomousPlatform#10]
Line 755: Correct the reference.

Checkout `revision_2` tag to see the state of the paper as submitted for the previous revision (to align line-numbers)

**Comment by mjseabright** [comment]
Fixed

**Comment by mjseabright** [comment]
Is there a reason you reopened this? I believe it's fixed by #15.

**Comment by markhedleyjones** [comment]
I reopened it so that when the relevant pull-request was merged it would automatically close this issue and add a message to this issue stating that it was closed by such and such a pull request. That way I/we can look back and find where/how this issue was closed (with a trace to the commit that closed it). However, I think because you merged the branch without me having approved it, GitHub doesn't consider the changes valid and therefore didn't close the associated issues. Or maybe it's because I added the closes #X references and not you. Hmm, I'm not sure. You're free to reclose this issue after you've read this. Essentially, you should never have to write Fixed as a comment in an issue because if you use the keywords correctly, GitHub will take care of linking the issues and pull-requests and close them when they're dealt with. Also, until your pull-requests have been approved by whoever you've asked for a review from, you shouldn't merge it (but it's fine for here) :smile:

**Comment by mjseabright** [comment]
Sorry about merging the pull request. I thought that I should merge it after checking the changes you requested. But rereading it, I can see that isn't the case. I'm glad I'm learning this stuff here and not on a 'more important' project where people might not be so understanding.

As for this issue, it is now fixed so I'll close it.
