### ISSUE TITLE
Add nomenclature table

### ISSUE THREAD

**Issue by markhedleyjones** [MarkHedleyJones/paper_autonomousPlatform#2]
Provide an alphabetically sorted nomenclature table with symbols, units and abbreviations (see author’s guide).

**Comment by mjseabright** [comment]
While reading through the paper, I tried to write down any terms that I thought needed explanation. Here they are:

- Pergola
- Block
- Canopy
- PSA (maybe?)

As for symbols, units and abbreviations, I don't think there is anything that needs it. But I guess that's not what the reviewer thinks...
