### ISSUE TITLE
Fix typo

### ISSUE THREAD

**Issue by markhedleyjones** [MarkHedleyJones/paper_autonomousPlatform#5]
Line 197: correct to “a torque of 388 Nm”.

Be aware that the line numbers are likely to have changed as a result of edits. You can checkout the `revision_2` tag to see the state of the paper at submission.

**Comment by mjseabright** [comment]
Fixed

**Comment by mjseabright** [comment]
I think this should be closed, as it's fixed by #15. Am I missing something?

**Comment by markhedleyjones** [comment]
No no, sorry. See my comment in #10. You're free to re-close.
