### ISSUE TITLE
Check relevance of mentioning Pioneer robot

### ISSUE THREAD

**Issue by markhedleyjones** [MarkHedleyJones/paper_autonomousPlatform#7]
Line 499: Why is the Pioneer robot mentioned here?

Checkout `revision_2` tag to see the state of the paper when it was submitted (to correct the line numbers)

**Comment by mjseabright** [comment]
I think the Pioneer mention is fine. It gives information on the suitability of the Pioneer to kiwifruit orchards. But just removing the two sentances is a perfectly fine option too, especially if it keeps a reviewer happy.
